[package]
name = "workspace-hack"
version = "0.1.0"
description = "workspace-hack package, managed by hakari"
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

# The parts of the file between the BEGIN HAKARI SECTION and END HAKARI SECTION comments
# are managed by hakari.

### BEGIN HAKARI SECTION
[dependencies]
aligned-vec = { version = "0.6", default-features = false, features = ["std"] }
bytes = { version = "1" }
concurrent-queue = { version = "2", default-features = false, features = ["std"] }
crossbeam-utils = { version = "0.8" }
crypto-common = { version = "0.1", default-features = false, features = ["std"] }
digest = { version = "0.10", features = ["mac", "std"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
either = { version = "1", features = ["serde", "use_std"] }
event-listener = { version = "5" }
form_urlencoded = { version = "1" }
futures = { version = "0.3", default-features = false, features = ["async-await", "executor"] }
futures-channel = { version = "0.3", features = ["sink"] }
futures-io = { version = "0.3" }
futures-sink = { version = "0.3", default-features = false, features = ["std"] }
futures-task = { version = "0.3", default-features = false, features = ["std"] }
futures-util = { version = "0.3", default-features = false, features = ["async-await-macro", "channel", "io", "sink"] }
getrandom = { version = "0.2", default-features = false, features = ["std"] }
hyper = { version = "1", features = ["client", "http1", "server"] }
hyper-util = { version = "0.1", features = ["client-legacy", "http1", "server", "service"] }
libc = { version = "0.2", features = ["extra_traits"] }
log = { version = "0.4", default-features = false, features = ["std"] }
memchr = { version = "2" }
num-traits = { version = "0.2" }
once_cell = { version = "1" }
ppv-lite86 = { version = "0.2", default-features = false, features = ["simd", "std"] }
rand_core = { version = "0.6", default-features = false, features = ["std"] }
regex-automata = { version = "0.4", default-features = false, features = ["dfa-build", "meta", "std"] }
regex-syntax = { version = "0.8" }
serde = { version = "1", features = ["alloc", "derive", "rc"] }
serde_core = { version = "1", features = ["alloc", "rc"] }
serde_json = { version = "1", features = ["raw_value"] }
sha2 = { version = "0.10" }
slab = { version = "0.4", default-features = false, features = ["std"] }
smallvec = { version = "1", default-features = false, features = ["const_new", "serde"] }
sqlx-core = { version = "0.8", features = ["_rt-tokio", "any", "json", "migrate", "offline"] }
sqlx-postgres = { version = "0.8", default-features = false, features = ["migrate", "offline"] }
thiserror = { version = "2" }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-core = { version = "0.1" }
trybuild = { version = "1", default-features = false, features = ["diff"] }
zerocopy = { version = "0.8", default-features = false, features = ["derive", "simd"] }

[build-dependencies]
aligned-vec = { version = "0.6", default-features = false, features = ["std"] }
bytes = { version = "1" }
concurrent-queue = { version = "2", default-features = false, features = ["std"] }
crossbeam-utils = { version = "0.8" }
crypto-common = { version = "0.1", default-features = false, features = ["std"] }
digest = { version = "0.10", features = ["mac", "std"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
either = { version = "1", features = ["serde", "use_std"] }
event-listener = { version = "5" }
form_urlencoded = { version = "1" }
futures = { version = "0.3", default-features = false, features = ["async-await", "executor"] }
futures-channel = { version = "0.3", features = ["sink"] }
futures-io = { version = "0.3" }
futures-sink = { version = "0.3", default-features = false, features = ["std"] }
futures-task = { version = "0.3", default-features = false, features = ["std"] }
futures-util = { version = "0.3", default-features = false, features = ["async-await-macro", "channel", "io", "sink"] }
getrandom = { version = "0.2", default-features = false, features = ["std"] }
hyper = { version = "1", features = ["client", "http1", "server"] }
hyper-util = { version = "0.1", features = ["client-legacy", "http1", "server", "service"] }
libc = { version = "0.2", features = ["extra_traits"] }
log = { version = "0.4", default-features = false, features = ["std"] }
memchr = { version = "2" }
num-traits = { version = "0.2" }
once_cell = { version = "1" }
ppv-lite86 = { version = "0.2", default-features = false, features = ["simd", "std"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
rand_core = { version = "0.6", default-features = false, features = ["std"] }
regex-automata = { version = "0.4", default-features = false, features = ["dfa-build", "meta", "std"] }
regex-syntax = { version = "0.8" }
serde = { version = "1", features = ["alloc", "derive", "rc"] }
serde_core = { version = "1", features = ["alloc", "rc"] }
serde_json = { version = "1", features = ["raw_value"] }
sha2 = { version = "0.10" }
slab = { version = "0.4", default-features = false, features = ["std"] }
smallvec = { version = "1", default-features = false, features = ["const_new", "serde"] }
sqlx-core = { version = "0.8", features = ["_rt-tokio", "any", "json", "migrate", "offline"] }
sqlx-postgres = { version = "0.8", default-features = false, features = ["migrate", "offline"] }
syn = { version = "2", features = ["extra-traits", "fold", "full", "visit", "visit-mut"] }
thiserror = { version = "2" }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-core = { version = "0.1" }
trybuild = { version = "1", default-features = false, features = ["diff"] }
zerocopy = { version = "0.8", default-features = false, features = ["derive", "simd"] }

[target.x86_64-unknown-linux-gnu.dependencies]
bitflags = { version = "2", default-features = false, features = ["std"] }

[target.x86_64-unknown-linux-gnu.build-dependencies]
bitflags = { version = "2", default-features = false, features = ["std"] }

### END HAKARI SECTION
